replicaCount: 2

image:
  repository: huzjie/dexworld
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8765

resources:
  limits:
    cpu: "1"
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
